# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@useDynLib StatComp22035
NULL

#' @title PageRank Algorithm
#' @description PageRank Algorithm using Rcpp
#' @param MA Matrix of adjacency
#' @param d damping rate
#' @param MaxIter Maximum number of iteration
#' @param IniVec Initial iteration vector
#' @return Score result of each node
#' @examples
#' \dontrun{
#' NumNode <- 50
#' nrow <- ncol <- NumNode
#' data(MA)
#' IniVec <- runif(NumNode, 0, 1)
#' Score <- PageRank(MA, 0.85, 100000, IniVec)
#' data <- data.frame(
#' ndex = 1:NumNode,  
#' value = Score
#' )
#' ggplot(data, aes(x=index, y=value)) + 
#' geom_bar(stat = "identity", width=0.5)
#' }
#' @export
PageRank <- function(MA, d, MaxIter, IniVec) {
    .Call('_StatComp22035_PageRank', MA, d, MaxIter, IniVec)
}

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N length of chain
#' @param mu parameter of bivariate normal distribution
#' @param sigma parameter of bivariate normal distribution
#' @param rho parameter of bivariate normal distribution
#' @param initial initial value
#' @return a random sample of size \code{N}
#' @export
gibbsC <- function(mu, sigma, rho, initial, N) {
    .Call('_StatComp22035_gibbsC', mu, sigma, rho, initial, N)
}

